name: CMake Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
  
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: automated_build
        files: |
          ${{github.workspace}}/build/Release/audy.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
